server:
  port: ${PORT_INVENTORY:8083}


openapi:
  dev-url: http://localhost:8082
  prod-url: http://127.0.0.1:8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3307/inventory-service?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123asd
  jpa:
    hibernate:
      ddl-auto: update    
    show-sql: true
  application:
    name: inventory-service
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      