server:
  port: ${PORT_ORDER_SERVICE:8082}

openapi:
  dev-url: http://localhost:8081
  prod-url: http://127.0.0.1:8081

server-inventory:
  url: ${URL_INVENTORY:http://inventory-service}

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/order-service?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123asd
  jpa:
    hibernate:
      ddl-auto: update    
    show-sql: true
  application:
    name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude: '*'
  endpoint:
    health:
      show-details: always


# resilinece4j properties

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s      
        
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s     
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        