server:
  port: 8081

openapi:
  dev-url: http://localhost:8081
  prod-url: http://127.0.0.1:8081

server-inventory:
  url: ${URL_INVENTORY:http://localhost:8082}

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/order-service?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123asd
  jpa:
    hibernate:
      ddl-auto: update    
    show-sql: true