spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      password: 123asd
      username: admin
      database: product-service
      authentication-database: admin

openapi:
  dev-url: http://localhost:8080
  prod-url: http://127.0.0.1:8080

inventory-service:
  url: ${ENDPOINT_INVENTORY:http://localhost:8082}
