server:
  port: ${PORT_PRODUCT_SERVICE:8081}

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      password: 123asd
      username: admin
      database: product-service
      authentication-database: admin
  application:
    name: product-service

openapi:
  dev-url: http://localhost:8080
  prod-url: http://127.0.0.1:8080

inventory-service:
  url: ${ENDPOINT_INVENTORY:http://localhost:8082}

  
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

      
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude: '*'
  endpoint:
    health:
      show-details: always


# resilinece4j properties

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s      
        
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s     
        
        
        
        
 